### ISSUE TITLE
No response to registering for an API Key

### ISSUE THREAD

**Issue by nzvengeance** [pmoon00/homebridge-intesis#3]
I have submitted a request in the form.

How long should this take?

I am eager to get my Integration up and running.

**Comment by pmoon00** [comment]
Hi there, we followed up with Intesis a while ago and they are still holding off on publicly giving tokens up.  Will follow up with them to see if anything has changed.

**Comment by nzvengeance** [comment]
I contacted Intesis and this is what they sent me:

```
Our API is thought for professionals that want to offer AC integration into their systems. 
We understand the need of our clients to get IntesisHome working with different home automation systems so we have developed the compatibility with Siri, Google Assistant, Amazon Alexa and IFTTT. 
 
In case you want to do an open-source integration, we have another line of product that might be of your interest:
https://www.intesisbox.com/en/wifi/gateways/
 
These are the IntesisBox version of our IntesisHome products. They don't go connected to our cloud system IntesisHome, rather go connected to your local WIFI and feature a simple protocol whose specification is linked in the web:
https://www.intesisbox.com/intesis/product/media/intesisbox_wmp_protocol_specs_en.pdf
```

**Comment by lmc4me** [comment]
I had a similar response recently. Any update for you pmoon00?

**Comment by pmoon00** [comment]
Hi guys,

Sorry Intesis have not moved on the matter.  Unfortunately it doesn't look like they are going to change their mind based on the response @NZVengeance received in July 2019.

Cheers
